import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { UiProvider } from './chakra-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Spotified',
  description: 'Generated by me',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UiProvider>{children}</UiProvider>
      </body>
    </html>
  );
}
